language: python
python:
  - "3.6"
  - "3.7"
notifications:
  email: false
# command to install dependencies
install:
  - pip install -r requirements.txt
  - pip install coveralls
# command to run tests
services:
  - postgresql
before_script:
  - psql -c 'CREATE DATABASE evoting_test_db;' -U postgres
  - curl -L https://codeclimate.com/downloads/test-reporter/test-reporter-latest-linux-amd64 > ./cc-test-reporter
  - chmod +x ./cc-test-reporter
  - ./cc-test-reporter before-build
script:
  - flake8
  - python manage.py migrate
  - coverage run manage.py test && coverage report
after_script:
  - coverage xml
  - ./cc-test-reporter after-build --exit-code $TRAVIS_TEST_RESULT
after_success:
  - coveralls

