# Generated by Django 2.2.9 on 2020-02-18 17:31

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='poll',
            name='created_on',
            field=models.DateTimeField(blank=True, default=datetime.datetime.now),
        ),
    ]
