# Generated by Django 2.2.9 on 2020-02-18 17:32

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0002_poll_created_on'),
    ]

    operations = [
        migrations.AlterField(
            model_name='poll',
            name='created_on',
            field=models.DateTimeField(default=datetime.datetime.now),
        ),
    ]
